name: Do a snap build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name : Remove Docker
        run: |
          # https://github.com/canonical/lxd-cloud/blob/f20a64a8af42485440dcbfd370faf14137d2f349/test/includes/lxd.sh#L13-L23
          sudo rm -rf /etc/docker
          sudo apt-get purge moby-buildx moby-engine moby-cli moby-compose moby-containerd moby-runc -y
          sudo iptables -P FORWARD ACCEPT

      - uses: actions/checkout@v3
        with:
          # Fetch all of history so DM can determine its own version from git.
          fetch-depth: 0

      - uses: snapcore/action-build@v1.0.9
        name: Build checkbox-phoronix snap
        id: build
        with:
          snapcraft-channel: latest/stable

      - name: Verify checkbox-phoronix snap
        run: |
          # Make sure it is installable.
          sudo snap install checkbox22
          sudo snap install --dangerous --classic ${{ steps.build.outputs.snap }}
